// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXJaE9d0CRuYJfVzfwScYQzHsS4PZ20YU',
    appId: '1:159449616255:web:2a7014be63fb32c134d44a',
    messagingSenderId: '159449616255',
    projectId: 'agri-hope-9e35c',
    authDomain: 'agri-hope-9e35c.firebaseapp.com',
    storageBucket: 'agri-hope-9e35c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVx88WaHnVgRdt83HboBVIqFpDXon7Zt8',
    appId: '1:159449616255:android:e7533d45c155a44734d44a',
    messagingSenderId: '159449616255',
    projectId: 'agri-hope-9e35c',
    storageBucket: 'agri-hope-9e35c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOyJyqsnrWCReTPVjCyerGCIqcvQvY5yk',
    appId: '1:159449616255:ios:8869a5b647069b3534d44a',
    messagingSenderId: '159449616255',
    projectId: 'agri-hope-9e35c',
    storageBucket: 'agri-hope-9e35c.firebasestorage.app',
    iosBundleId: 'com.example.agriHope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOyJyqsnrWCReTPVjCyerGCIqcvQvY5yk',
    appId: '1:159449616255:ios:8869a5b647069b3534d44a',
    messagingSenderId: '159449616255',
    projectId: 'agri-hope-9e35c',
    storageBucket: 'agri-hope-9e35c.firebasestorage.app',
    iosBundleId: 'com.example.agriHope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXJaE9d0CRuYJfVzfwScYQzHsS4PZ20YU',
    appId: '1:159449616255:web:5b4f03d11d31f2e434d44a',
    messagingSenderId: '159449616255',
    projectId: 'agri-hope-9e35c',
    authDomain: 'agri-hope-9e35c.firebaseapp.com',
    storageBucket: 'agri-hope-9e35c.firebasestorage.app',
  );
}
